version: "3.2"

services:
  tika:
    image: logicalspark/docker-tikaserver
    ports:
      - 9998:9998
    extra_hosts:
      - "dockerhost: 10.200.10.1"

  php:
    build:
      context: ../
      dockerfile: ./docker-compose/php/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: ../web
        target: /var/www/public
    extra_hosts:
      - "dockerhost: 10.200.10.1"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
    extra_hosts:
          - "dockerhost: 10.200.10.1"